### ISSUE TITLE
Show Tab Group Count In List View

### ISSUE THREAD

**Issue by hharnisc** [hharnisc/tabbie#10]
Related to #3

**Comment by AkarshSatija** [comment]
Added here. @hharnisc 
#16  [https://github.com/hharnisc/tabbie/pull/16]

**Comment by hharnisc** [comment]
Playing with this design:

![show tab groups](https://cloud.githubusercontent.com/assets/1388079/21596851/c5906728-d106-11e6-83f2-e47b59e12901.png)
