### ISSUE TITLE
Open tabs in existing window

### ISSUE THREAD

**Issue by ersin-ertan** [hharnisc/tabbie#12]
An additional feature to open tabs in existing window, if chrome is open.

**Comment by hharnisc** [comment]
Have gotten quite a few requests for this one. Need to think a bit on the UX, but an early thought is a  dropdown button (sort of like this one on Product Hunt). 

<img width="105" alt="screen shot 2017-01-01 at 9 23 27 am" src="https://cloud.githubusercontent.com/assets/1388079/21581744/34525724-d004-11e6-9e61-f42b49ce9a5e.png">

If you just click the button it opens in a new window. Hovering over the down arrow shows an "open in current window", clicking would do as advertised. 

It's possible that opening in the current window would be the default, but hard to tell without building and then measuring it.

**Comment by Primigenus** [comment]
How about a cmd modifier? When you click a link on a webpage and hold down cmd, it opens it in a new tab. Having this work the same way could be intuitive, although it might be invisible initially.

**Comment by ersin-ertan** [comment]
I disagree, the cmd modifier would not be intuitive from the browsing/contextual point of and here's why.

Using a chrome extension, you need not be at a new tab to open more tabs(use Tabbie) and can continue reading the site of your current context, if required. The 'open' action should have the default behaviour of opening the tabs within the current browsing context/chrome window, unless otherwise instructed.

A standard click follows the link within the browsing context/window(thus the experience is synchronous). This grants 'back' and 'forward' navigation. Also the 'close tab', 'restore tab', 'new tab' functionality works with the tab at the top of your 'action' stack for the current chrome window. (with the exception of open in new window, which is at the second position in the left click menu) There are more cmd+... operators doing work within the current browsing context/chrome window than there are with new window contexts, so I would assume that a standard click would operate within my current browsing context/chrome window.

Because standard click is now doing what cmd click would do(preserving browsing context and opening tabs asynchronously in your current chrome window), the left click menu options slide one position up, thus cmd click would trigger, by default, the new option at position one, which is 'open links in new window'

I consider the important interactions to be: open async. via click, open sync. in current browsing context via cmd+shift+click, open sync. in new window via fn+shift+click, and open async. in new window via (don't know)

P.S. I have considered the use case of opening incognito windows too, but it seems like an unlikely use-case.
Feedback is welcomed.
