### ISSUE TITLE
Configuration Request: Toggle Tabbie Icon Monochrome

### ISSUE THREAD

**Issue by hharnisc** [hharnisc/tabbie#20]
Could be a nice feature to add to a configuration screen. Not sure if it's possible to change the chrome extension icon though.

**Comment by Primigenus** [comment]
Sounds like going down the path of having a bunch of settings just to have them, but ultimately cluttering up the app.

**Comment by sepehr** [comment]
The good old [gone] Readability chrome extension had a config option to swap extension's icon with a monochrome version. So at least it **was** possible.

Even though I like it to be as minimal as possible, I don't think adding a configuration page is "cluttering" up the extension. I'd like to tweak the tools that I use on a daily basis to my likings. Not sure about the icon, but I'm sure there are a lot of people that tend to tweak their tools on such details.  

Have a look, a little too bold, right?

![screen shot 2017-01-03 at 4 02 19 pm](https://cloud.githubusercontent.com/assets/23576/21607836/094e0d40-d1ce-11e6-8868-eb3deecc4567.png)

Monochrome icon or not, thanks for this perfect extension.

**Comment by hharnisc** [comment]
Thank you for the feedback @sepehr! In that view it's pretty clear Tabbie sticks out. 

It's funny because I've got some more color my extension menu:

<img width="139" alt="screen shot 2017-01-03 at 10 12 27 am" src="https://cloud.githubusercontent.com/assets/1388079/21614018/77171d98-d19d-11e6-8446-630431877993.png">

So I think it comes down to personal preferences. I'd like to note that I'm trying to avoid the need for a settings page, and keep things as simple as possible. If a settings page does somehow sneak into Tabbie, I'll probably add a feature to make the icon monochrome.
