### ISSUE TITLE
vanilla JS for UI

### ISSUE THREAD

**Issue by raygesualdo** [hharnisc/tabbie#23]
Did you consider using Vue, React, etc.? Sorry, not trying to be that guy. More wondering how you arrived at your solution.

**Comment by hharnisc** [comment]
Great question! I started this project out to solve a pretty specific problem for myself and it has grown quite a bit since the initial prototype. The mentality being to spend as little time as possible on it to solve the problem and keep things simple - after all it's just me using this thing right? 😄. So at the time bringing in Vue, React, etc. didn't make sense to me. But as this has grown, it's getting more difficult to maintain and extend with vanilla JS. So something like [react boilerplate](https://www.npmjs.com/package/react-chrome-extension-boilerplate) (or some vue.js equivalent) might be better in the long run as this project matures.

**Comment by raygesualdo** [comment]
If you're not opposed, I'd like to put together a React-based example using [create-react-app](https://github.com/facebookincubator/create-react-app/) in another repo to see what a refactor could look like.

**Comment by hharnisc** [comment]
Not at all! That sounds awesome!

**Comment by raygesualdo** [comment]
Excellent! I'll try to get a first pass up tomorrow. I'll link to the repo here when it's up.

**Comment by arkon** [comment]
I'm kind of wondering what using web components would be like. Seems like a good place to tinker with them since it's sandboxed to Chrome anyway. 🤔

**Comment by hharnisc** [comment]
@arkon pretty nice only need things to work in the Chrome sandbox 😄 I'd like to avoid using web components for now, since the feature set is relatively small and we'd have to do extra work to get a11y features working smoothly.

**Comment by hharnisc** [comment]
Just wanted to give you a heads up @raygesualdo I've started playing around with adding React on this repo with the branch name `react`. Still very early so stuff will certainly move around

**Comment by raygesualdo** [comment]
Awesome @hharnisc! I got an example spun up with create-react-app. You can view it here: https://github.com/raygesualdo/retabbie

Currently, it doesn't function because I haven't been able to mock the chrome extension API. I may take a stab at that. But all the functions that interact with that API are unchanged.

Ideas for continued improvement:
- [ ] Use more `async/await` in utilities
- [ ] Create single "promisify" wrapper for all the Chrome APIs
- [ ] Implement UUIDs with tab groups
- [ ] Add and remove tab groups based on UUID

**Comment by raygesualdo** [comment]
@hharnisc Did you get a chance to look at the refactor? Not trying to be pushy!!! I know you're busy but wanted to check in.

**Comment by hharnisc** [comment]
Have had a pretty busy week and hadn't had a chance yet. But I just took a quick look and this is looking awesome. I'll be out the next week so I won't be able to dig into it until then. On that list there the biggest thing in my mind is the wrapper for Chrome APIs. Would want to make sure this works with the current data people already have.

**Comment by raygesualdo** [comment]
Absolutely. Wrapper would only be a syntactical nicety. Wouldn't change how data is pulled from `chrome.storage.sync`.

**Comment by hharnisc** [comment]
Hey @raygesualdo had a chance to look at the refactor you've got in place. A couple things I noticed

- It would be nice to see components broken up into smaller files
- Was hoping to break out google analytics calls into their own actions
- Would like to see entirely stateless components
- Create react app implementation looks pretty clean, nice work there!

Would you mind taking a look at the [react branch](https://github.com/hharnisc/tabbie/tree/react) in this repo? I've been using browserify (and related tooling) to get a pretty nice DevX and breaking things up into smaller components. The other thing is that I'm using Redux patterns more like an event bus - and eventually plan on calling google analytics somewhere in the action dispatch chain (much like how https://github.com/zeit/hyper does it).

**Comment by raygesualdo** [comment]
Hi @hharnisc! Below are my thoughts:

1. The application in my repo could very easily be broken up into more components. It may not be readily apparent because I used styled-components, but `common.js` contains all individual components. I kept them in a single file so it was easy to import. They could just as easily be split into multiple files. `App.js` could also be split up further as well.
1. With the exception of `Container.js`, all the components are stateless components. 
1. I took a look at the react branch. Lots of good things in there! I can see what you're saying about smaller components as well. A thought about redux: most small applications (which I think applies in Tabbie's case) don't require a full redux implementation. It's a lot of cognitive overhead for very little gain, IMHO. Feel free to push back on that. This is why I created the `Container.js` in my repo. It is effectively acting as our state management layer. Tabbie's functionality has so little surface area (which is a good thing) that it doesn't require extensive logic to get everything working. Redux seems to add complication when none is needed. Thoughts?

**Comment by hharnisc** [comment]
Hey @raygesualdo so great thought's you've laid out here! I think we share a lot of thoughts around keeping things simple and I can see where you're coming from with points 1 and 2.

Did a bit more thinking around your 3rd point around using Redux. I think you're exactly right there IF the current feature set was complete. With some of the features I'd like to add, particularly #9 #10 #11 #26 add enough complexity to warrant the use of Redux in my mind. These are features that could add more control surfaces that would be difficult to manage with a hand rolled solution.

Another big one is #28 - to fully solve that problem a backend solution would need to be implemented. I think that using Redux as the event bus is going to de-couple the syncing mechanism (chrome local storage, sync storage or some other backend). You'd likely have to build something that looked like Redux here either way.

Really enjoyed your thoughts on this, it's great to have a push to keep things as simple as possible!

**Comment by raygesualdo** [comment]
Hi @hharnisc, I'm glad we've been able to talk through this as well!

I understand now why you want to include Redux. It will add significant value when expanding Tabbie's feature set. What should the next steps be for continuing development here? I would love to be a part of the React/Redux switch-over.

Additionally, I've been thinking about a backend solution. I think there may be a way to implement some serverless architectures combined with object stores to provide what Tabbie needs from a backend solution for free. It's a very simple solution, but I think it could work. It could also be open-sourced so others could host it themselves. We can continue discussing here or feel free to DM me on [Twitter](https://twitter.com/RayGesualdo).

**Comment by hharnisc** [comment]
Hey @raygesualdo sorry for taking so long to get back to you here. Have been playing around with this the past couple weekends and needed some solo time to figure out how to architect the bridge between redux and chrome storage. I ended up using [middleware](https://github.com/hharnisc/tabbie/blob/master/src/middleware/chromeStorage.js) to handle the side effects. There's some room for improvement, but I think this is looking pretty clean.

The other cool thing here is that middleware could be used to hook into another storage engine. You pretty much just need to hook into the `ADD_*/REMOVE_*` events. 

Would love to hear your thoughts around implementing a serverless backend. I'd imagine they're free until you hit a certain level of traffic. At the moment this is pretty low volume so I bet this would be in the free tier of most services for a while.

**Comment by hharnisc** [comment]
@raygesualdo would you be up for opening another issue hear with your thoughts on backend solutions?
