### ISSUE TITLE
No way to know which URLs are behind an entry

### ISSUE THREAD

**Issue by kurtextrem** [hharnisc/tabbie#3]
Maybe add a tooltip (or title attribute) which lists all of the saved URLs

**Comment by hharnisc** [comment]
Would love to see this feature too @kurtextrem! I can't quite picture what this feature looks like in implementation. Could see a tooltip or even a details page depending on the use case.

**Comment by arkon** [comment]
Perhaps an accordion-like UI? 🤔

**Comment by ChJJin** [comment]
I think this is an important feature. How about a collapse style UI ?

**Comment by AkarshSatija** [comment]
Added here. #16  [https://github.com/hharnisc/tabbie/pull/16]

**Comment by hharnisc** [comment]
Been playing with this design, displays a few favicons and the count on the list page. 

![show tab groups](https://cloud.githubusercontent.com/assets/1388079/21596877/366bde46-d107-11e6-8f5e-af99c8937b08.png)

When clicking on the `+ 8 more` or favicons you see the details dialog. It's the list of lists design pattern.

![show tab groups open](https://cloud.githubusercontent.com/assets/1388079/21596886/4c54ebc6-d107-11e6-942e-df87694bb4d9.png)
