### ISSUE TITLE
How do you even use this?

### ISSUE THREAD

**Issue by hallshouse** [hharnisc/tabbie#32]
After installing Tabbie 1.1.3 in Chrome v56.0.2924.87 (64-bit) on Windows10, If I go to a web page and want to add it to Tabbie, I left click the Tabbie icon in the toobar and get the menu with the first item being "Tabbie - Material New Tab Page", then options (greyed out), the remove, hide and manage Chrome extensions.

When i click on the Tabbie - Material New Tab Page item it opens the Chrome Extensions > Tabbie already installed panel.

How do you use this extension?

**Comment by hharnisc** [comment]
Hey @hallshouse I think you're looking for https://github.com/jariz/tabbie.
